### ISSUE TITLE
RestProxy needs to take baseURL as a parameter

### ISSUE THREAD

**Issue by RikkiGibson** [Azure/autorest-clientruntime-for-java#207]
The base URL of a service depends on the environment indicated by your credentials.
https://github.com/Azure/azure-sdk-for-java/blob/4e25b6c5b289af7e1bb3a619a246b37574a07412/azure-mgmt-storage/src/main/java/com/microsoft/azure/management/storage/implementation/StorageManager.java#L48

https://github.com/Azure/autorest-clientruntime-for-java/blob/master/azure-client-runtime/src/main/java/com/microsoft/azure/AzureEnvironment.java#L35

RestProxy needs to be able to take this baseURL, perhaps at the time that `RestProxy.create` is called.

**Comment by daschult** [comment]
I remember having this discussion with Jianghao. At the time I remember we chose to just use the Host annotation because it was simpler. I think there's an AzureHost annotation that takes an Endpoint as an argument, but AzureHost is defined in azure-clientruntime, not just clientruntime, so I don't think RestProxy can access it.

In short, I think you might be correct.

**Comment by RikkiGibson** [comment]
This is blocking some work on the AutoRest.java tests, so I'll probably pick this up on Monday.

**Comment by RikkiGibson** [comment]
I'm starting by just adding another parameter to SwaggerInterfaceParser, but I'm concerned in general about the parameter list for RestProxy.create growing excessively. Maybe a config object would be appropriate. A Config object might be appropriate.

**Comment by daschult** [comment]
I think adding another parameter is fine for now. I think we'll do a bit of refactoring before all of this is done, so I'd keep it simple.

**Comment by RikkiGibson** [comment]
Resolved in #219
