### ISSUE TITLE
v2: NettyClient.ResponseContentFlowable no reentrancy protection

### ISSUE THREAD

**Issue by davidmoten** [Azure/autorest-clientruntime-for-java#389]
Just had a look at `NettyClient.ResponseContentFlowable`. Implementations of `Flowable` are always tricky things so it drew my eye.

I noticed that it is marked as not thread safe but the reentrancy synchronous use case can provoke stack overflow at the moment.

In particular, `request(1)` calls `emitContent` which calls `subscriber.onNext` which may call `request(1)` and bingo after a few thousand items are emitted you have stack overflow. 

This is not hard to fix for the synchronous case. Instead of emitting immediately, add the `data.content()` to a queue and call a `drain()` method. If currently draining (check a boolean field) then do nothing otherwise emit the contents of the queue.

**Comment by davidmoten** [comment]
I notice now that the only use of `ResponseContentFlowable` overrides the `request` and `cancel` methods (without referencing `super`) and does no request accounting.

**Comment by RikkiGibson** [comment]
Thanks for the guidance. I've had problems with `request` calling `subscriber.onNext` in the past which I think I worked around with unnecessary use of `.observeOn()`. I'll have another look considering the approach you've suggested.

Regarding the request accounting: the indirection around request() and cancel() in here could be made more clear and maybe refactored to have this key information strewn about fewer areas, but if I'm understanding what you're saying correctly, this part looks sound to me.

- The ResponseContentFlowable constructor takes a Subscription as an argument which is used to interpret the Rx `request` and `cancel` methods in Netty terms (channel read, channel close). Since ResponseContentFlowable is also a Subscription it has implementations of `request` and `cancel` that do request accounting and call into the `request` and `cancel` on the given Subscription.

- ResponseContentFlowable contains `long chunksRequested` which is referenced in [channelReadComplete](https://github.com/Azure/autorest-clientruntime-for-java/blob/v2/client-runtime/src/main/java/com/microsoft/rest/v2/http/NettyClient.java#L488) after each Netty read completes to determine if another Netty read needs to be initiated

**Comment by RikkiGibson** [comment]
Addressed in #406
