### ISSUE TITLE
 HTTP Date header

### ISSUE THREAD

**Issue by rickle-msft** [Azure/autorest-clientruntime-for-java#391]
I think it would be helpful if the runtime added the Date header by default when it generates the HTTP request since it is a standard header that we attach to every request.

**Comment by RikkiGibson** [comment]
Because most services don't depend on requests containing a Date header, and most HTTP applications like browsers or curl don't send this header by default, I think the most we would probably do for this is provide a built-in AddDatePolicyFactory which you can add to your pipeline using `HttpPipelineBuilder.withAddDatePolicy()`.

**Comment by RikkiGibson** [comment]
If this seems reasonable we will probably go forward with such a change. AddDatePolicyFactory already exists scoped to some tests, it can just be pulled out. Probably needs to be made lazy with Single.defer such that every time the request passes through a fresh date value gets added.
