### ISSUE TITLE
[v3] adoption of slf4j and removing custom logger API from the runtime

### ISSUE THREAD

**Issue by anuchandy** [Azure/autorest-clientruntime-for-java#557]
#### [Details from @JonathanGiles]:

1. Do you think it is beneficial to abstract the logging framework being used? In my opinion for v3 / track two, we should just adopt slf4j and remove the custom logger API from the runtime, including HttpPipelineLogger, HttpPipelineLogLevel, Slf4jLogger, and SystemOutLogger.
2. This has the flow-on effect of removing the need for HttpPipelineOptions, which could be removed.
3. This also means that AbstractPipelinePolicy can be removed. In fact, this class is inconsistently applied – some policies extend from it to use its logging functionality, and others, such as HttpLoggingPolicy make use of the slf4j logger directly.

**Comment by anuchandy** [comment]
@JonathanGiles Agree with you, all the logging should ideally go through slf4j.

It seems HttpPipelineLogger is used by storage [logger](https://github.com/Azure/azure-storage-java/blob/master/src/main/java/com/microsoft/azure/storage/blob/LoggingFactory.java), it also uses slf4j.

We might want to first understand the reason for storage to use this pattern, may be @JeffreyRichter might be able to share the history.

**Comment by JeffreyRichter** [comment]
There is a ton of history around this. I'll do my best to summarize...

A main priority of the client libraries is to NOT take any dependencies on other libraries; just the language platform libraries. And so, the original logger design had 2 callback methods: one for shouldLog (which takes a log level like info, warning or error) and returns a bool. And if shouldLog returns true, then a Log method that takes the level and the string message to log. shouldLog is called first and if it returns false, then the string to log is NOT created in an effort to avoid the memory/CPU hit of constructing the string to log. In addition, shouldLog is a method (as opposed to just a simple level check) because I wanted to enable dynamic configuration of this. For example, the app may startup and log only errors but then set some flag to turn on logging of info and above. And then, dynamically change the flag again to go back to logging only errors. This also enables the ability to log info and errors while skipping warnings if desired. This scenario (of logging info and errors and not warnings) is unlikely to desired in real-life. However, imagine an app adds some additional app-defined log levels (like file uploads or file downloads). By having shouldLog be a callback, the method can return true for all file uploads, false for file downloads, and true for errors, and false for info or warnings. This kind of flexibility did turn out to useful when we were building Azure's AzCopy utility.

For Java, I do not consider myself plugged in well with the community so I trust other people to help guide me. I was told that, in Java, slf4j is THE logging framework and that confidence is extremely high that this will never change in the future. I'm always dubious of comments like this but I heard multiple times from multiple people and so for Storage's Java SDK, we said OK, we'll take a dependency on slf4j. In no other language did people have this kind of confidence on a single one-logger-to-rule-them-all technology. 

I left the team before all this work was completed and so it looks like the logger now uses some hodgepodge of both the callbacks and slf4j. I agree that only one technology should be used consistently. 

Hope this helps.

**Comment by JonathanGiles** [comment]
Thanks for clarifying Jeff, this is really useful insight.

**Comment by JonathanGiles** [comment]
@anuchandy Is your plan to follow-through on my feedback above?

**Comment by anuchandy** [comment]
@JonathanGiles From Jeffery's comment I understand that custom logging framework offer dynamic configuration, that way different parts of the application can dynamically decide whether to log or not during execution time. In real life I'm not sure how common it is for applications to use this functionality. 
Couldn't find any popular logging framework offering such a callback to enable/disable dynamically.

Let's follow your guideline, will remove these types for now. We can bring them back if we find there is a need for it as we build libs on the top of common module.

**Comment by anuchandy** [comment]
@JonathanGiles, @conniey custom logger api has been removed.

**Comment by anuchandy** [comment]
Closing this. We've an issue opened already on sdk repo to investigate common logger design.
