### ISSUE TITLE
[v3] Adding overload for HttpPipeline to accept List<HttpPipelinePolicy>

### ISSUE THREAD

**Issue by conniey** [Azure/autorest-clientruntime-for-java#575]
Would it be possible to add an overload to [HttpPipeline](https://github.com/Azure/autorest-clientruntime-for-java/blob/v3/client-runtime/src/main/java/com/microsoft/rest/v3/http/HttpPipeline.java#L28) to take `List<HttpPipelinePolicy>` or similar?

We have logic, based on whether or not some configuration is set, to add in additional policies or not. Consequently, we have to call `policies.ToArray(new HttpPipelinePolicy[0])`

Example:
[AzConfigTest.cs](https://github.com/Azure/azure-sdk-for-java/blob/azconfig/applicationconfig/client/src/test/java/com/azure/applicationconfig/AzConfigTest.java#L91-L94)

```java
    List<HttpPipelinePolicy> policies = getDefaultPolicies(credentials);
    policies.add(interceptorManager.initRecordPolicy());

    pipeline = new HttpPipeline(client, policies.toArray(new HttpPipelinePolicy[0]));
    
```

**Comment by anuchandy** [comment]
@conniey we are not taking List intentionally today, the reason is - With the current pipeline ctr signature we make it clear to the user that pipeline is immutable once created. By taking a List we are introducing uncertainty,  i.e. it's not clear to the user that what will be our runtime behavior if he adds, removes policies or change policies order in the original List passed to the pipeline ctr. This will be the pipeline behavior across all languages.

Happy to hear your thoughts on this.

**Comment by conniey** [comment]
@anuchandy Thanks for explaining! What about something like Iterator? I think that suggests that you want a set that you can iterate over.

I noticed in the code that the reference to that array is set [HttpPipeline.java#L31](https://github.com/Azure/autorest-clientruntime-for-java/blob/v3/client-runtime/src/main/java/com/microsoft/rest/v3/http/HttpPipeline.java#L31), so it would be still possible to modify the pipeline by updating that array since we're pointing to it.

```java
var array = new HttpPipelinePolicy[] { new FooPolicy(); }
var pipeline = new HttpPipeline(array);

// Now the pipeline has another policy that is not FooPolicy.
array[0] = new BarPolicy();
```

I was thinking from the .NET perspective where, we create a new set and pass pointers to the objects themselves rather than point to the set itself. For example:
```java
class MyClazz {
  void MyMethod() {
    var array = new HttpPipelinePolicy[] { new FooPolicy(); }
    var pipeline = new HttpPipeline(array);

    // the pipeline is unaffected.
    array[0] = new BarPolicy();
  }
}
class HttpPipeline {
  private final HttpPipelinePolicy[] policies;
  HttpPipeline(List<HttpPipelinePolicy> policies) {
    // this would be OK since the method would allocate a new array
    // that doesn't refer to given collection
    this.policies = policies.toArray();
  }
}
```

Thoughts, @JonathanGiles?

**Comment by JonathanGiles** [comment]
If it were me I would solve the issue of 'users think they can modify a list of elements after passing it to the HttpPipeline' by documentation, rather than forcing them to have a worse API experience. Furthermore,It appears that even now that the HttpPipeline policies are not immutable - if I modify the array elements in place, after it has been passed to the HttpPipeline, by calling `pipelinePolicies()[0] = null` for example, it looks as if I can change them after construction time?

We should state that a copy of the List (or array!) is made, and then the original list is discarded.

**Comment by anuchandy** [comment]
Thanks @conniey @JonathanGiles . Agreed let's do following:

1. Support inputting List and array
2. In both cases copy the input contents (policies) to local array
3. Make it clear in the doc that we make copy of input and not directly uses the input after that

**Comment by anuchandy** [comment]
Implemented, see linked PR. Closing.
